import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ClerkProvider } from "@clerk/nextjs";
import { getClerkLocalization, Locale } from "@/i18n/config";
import { ConvexClientProvider } from "@/components/site/convex-client-provider";
import { ThemeProvider } from "@/components/site/theme-provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const localization = getClerkLocalization(locale as Locale);

  const messages = await getMessages();

  return (
    <ClerkProvider localization={localization}>
      <html lang={locale}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="system"
            enableSystem
          >
            <NextIntlClientProvider messages={messages}>
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
